#!/usr/bin/env bash

where=${1:-.}
tests=$1

if [ -d $where ]; then
  tests=`find $where -type f -name '*-test.*' -not -path './node_modules/*'`
fi

ln -s `pwd` node_modules/babel-plugin-react-autoprefix

./node_modules/babel-cli/bin/babel-node.js $tests

rm node_modules/babel-plugin-react-autoprefix
